# Site
name: 'PhoenixVPN'
description: 'PhoenixVPN is a free VPN for PC.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/download-phoenix-vpn-for-pc/'
disqus: 'PhoenixVPN'
email: 'PhoenixVPNinfo@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Sal
      site:          https://phoenixvpn.github.io/
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Phoenixvpn, the website you're currently previewing. I hope you like it!"
      email:          phoenixvpnsal@gmail.com
      twitter:        https://twitter.com/phoenixvpn

    jane:
      name:           Jane
      site:           https://phoenixvpn.github.io/
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          phoenixvpnjane@gmail.com
      twitter:        https://twitter.com/phoenixvpn
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]